title Remove invalid ent module
rd /s/q .\addons_ent_remove
md addons_ent_remove
move /y .\addons_ent\account_taxcloud .\addons_ent_remove\
move /y .\addons_ent\currency_rate_live .\addons_ent_remove\
move /y .\addons_ent\delivery_bpost .\addons_ent_remove\
move /y .\addons_ent\delivery_dhl .\addons_ent_remove\
move /y .\addons_ent\delivery_easypost .\addons_ent_remove\
move /y .\addons_ent\delivery_fedex .\addons_ent_remove\
move /y .\addons_ent\delivery_ups .\addons_ent_remove\
move /y .\addons_ent\delivery_usps .\addons_ent_remove\
move /y .\addons_ent\l10n_ae .\addons_ent_remove\
move /y .\addons_ent\l10n_ar .\addons_ent_remove\
move /y .\addons_ent\l10n_ar_reports .\addons_ent_remove\
move /y .\addons_ent\l10n_at .\addons_ent_remove\
move /y .\addons_ent\l10n_at_reports .\addons_ent_remove\
move /y .\addons_ent\l10n_au .\addons_ent_remove\
move /y .\addons_ent\l10n_au_aba .\addons_ent_remove\
move /y .\addons_ent\l10n_au_reports .\addons_ent_remove\
move /y .\addons_ent\l10n_be .\addons_ent_remove\
move /y .\addons_ent\l10n_be_coda .\addons_ent_remove\
move /y .\addons_ent\l10n_be_hr_payroll .\addons_ent_remove\
move /y .\addons_ent\l10n_be_hr_payroll_account .\addons_ent_remove\
move /y .\addons_ent\l10n_be_hr_payroll_fleet .\addons_ent_remove\
move /y .\addons_ent\l10n_be_intrastat .\addons_ent_remove\
move /y .\addons_ent\l10n_be_intrastat_2019 .\addons_ent_remove\
move /y .\addons_ent\l10n_be_invoice_bba .\addons_ent_remove\
move /y .\addons_ent\l10n_be_reports .\addons_ent_remove\
move /y .\addons_ent\l10n_bo .\addons_ent_remove\
move /y .\addons_ent\l10n_bo_reports .\addons_ent_remove\
move /y .\addons_ent\l10n_br .\addons_ent_remove\
move /y .\addons_ent\l10n_br_reports .\addons_ent_remove\
move /y .\addons_ent\l10n_ca .\addons_ent_remove\
move /y .\addons_ent\l10n_ca_check_printing .\addons_ent_remove\
move /y .\addons_ent\l10n_ch .\addons_ent_remove\
move /y .\addons_ent\l10n_ch_reports .\addons_ent_remove\
move /y .\addons_ent\l10n_cl .\addons_ent_remove\
move /y .\addons_ent\l10n_cl_reports .\addons_ent_remove\
move /y .\addons_ent\l10n_co .\addons_ent_remove\
move /y .\addons_ent\l10n_co_edi .\addons_ent_remove\
move /y .\addons_ent\l10n_co_reports .\addons_ent_remove\
move /y .\addons_ent\l10n_cr .\addons_ent_remove\
move /y .\addons_ent\l10n_de .\addons_ent_remove\
move /y .\addons_ent\l10n_de_reports .\addons_ent_remove\
move /y .\addons_ent\l10n_de_skr03 .\addons_ent_remove\
move /y .\addons_ent\l10n_de_skr04 .\addons_ent_remove\
move /y .\addons_ent\l10n_do .\addons_ent_remove\
move /y .\addons_ent\l10n_do_reports .\addons_ent_remove\
move /y .\addons_ent\l10n_ec .\addons_ent_remove\
move /y .\addons_ent\l10n_es .\addons_ent_remove\
move /y .\addons_ent\l10n_es_real_estates .\addons_ent_remove\
move /y .\addons_ent\l10n_es_reports .\addons_ent_remove\
move /y .\addons_ent\l10n_et .\addons_ent_remove\
move /y .\addons_ent\l10n_et_reports .\addons_ent_remove\
move /y .\addons_ent\l10n_eu_service .\addons_ent_remove\
move /y .\addons_ent\l10n_fr .\addons_ent_remove\
move /y .\addons_ent\l10n_fr_certification .\addons_ent_remove\
move /y .\addons_ent\l10n_fr_fec .\addons_ent_remove\
move /y .\addons_ent\l10n_fr_hr_payroll .\addons_ent_remove\
move /y .\addons_ent\l10n_fr_pos_cert .\addons_ent_remove\
move /y .\addons_ent\l10n_fr_reports .\addons_ent_remove\
move /y .\addons_ent\l10n_fr_sale_closing .\addons_ent_remove\
move /y .\addons_ent\l10n_generic_coa .\addons_ent_remove\
move /y .\addons_ent\l10n_gr .\addons_ent_remove\
move /y .\addons_ent\l10n_gr_reports .\addons_ent_remove\
move /y .\addons_ent\l10n_gt .\addons_ent_remove\
move /y .\addons_ent\l10n_hk .\addons_ent_remove\
move /y .\addons_ent\l10n_hn .\addons_ent_remove\
move /y .\addons_ent\l10n_hr .\addons_ent_remove\
move /y .\addons_ent\l10n_hr_reports .\addons_ent_remove\
move /y .\addons_ent\l10n_hu .\addons_ent_remove\
move /y .\addons_ent\l10n_hu_reports .\addons_ent_remove\
move /y .\addons_ent\l10n_in .\addons_ent_remove\
move /y .\addons_ent\l10n_in_hr_payroll .\addons_ent_remove\
move /y .\addons_ent\l10n_in_purchase .\addons_ent_remove\
move /y .\addons_ent\l10n_in_reports .\addons_ent_remove\
move /y .\addons_ent\l10n_in_sale .\addons_ent_remove\
move /y .\addons_ent\l10n_in_schedule6 .\addons_ent_remove\
move /y .\addons_ent\l10n_in_stock .\addons_ent_remove\
move /y .\addons_ent\l10n_it .\addons_ent_remove\
move /y .\addons_ent\l10n_jp .\addons_ent_remove\
move /y .\addons_ent\l10n_jp_reports .\addons_ent_remove\
move /y .\addons_ent\l10n_lu .\addons_ent_remove\
move /y .\addons_ent\l10n_lu_reports .\addons_ent_remove\
move /y .\addons_ent\l10n_ma .\addons_ent_remove\
move /y .\addons_ent\l10n_ma_reports .\addons_ent_remove\
move /y .\addons_ent\l10n_mx .\addons_ent_remove\
move /y .\addons_ent\l10n_mx_edi .\addons_ent_remove\
move /y .\addons_ent\l10n_mx_edi_customs .\addons_ent_remove\
move /y .\addons_ent\l10n_mx_edi_external_trade .\addons_ent_remove\
move /y .\addons_ent\l10n_mx_edi_landing .\addons_ent_remove\
move /y .\addons_ent\l10n_mx_edi_payment .\addons_ent_remove\
move /y .\addons_ent\l10n_mx_edi_payment_bank .\addons_ent_remove\
move /y .\addons_ent\l10n_mx_reports .\addons_ent_remove\
move /y .\addons_ent\l10n_nl .\addons_ent_remove\
move /y .\addons_ent\l10n_nl_intrastat .\addons_ent_remove\
move /y .\addons_ent\l10n_nl_reports .\addons_ent_remove\
move /y .\addons_ent\l10n_no .\addons_ent_remove\
move /y .\addons_ent\l10n_no_reports .\addons_ent_remove\
move /y .\addons_ent\l10n_nz .\addons_ent_remove\
move /y .\addons_ent\l10n_pa .\addons_ent_remove\
move /y .\addons_ent\l10n_pe .\addons_ent_remove\
move /y .\addons_ent\l10n_pl .\addons_ent_remove\
move /y .\addons_ent\l10n_pl_reports .\addons_ent_remove\
move /y .\addons_ent\l10n_pt .\addons_ent_remove\
move /y .\addons_ent\l10n_ro .\addons_ent_remove\
move /y .\addons_ent\l10n_ro_reports .\addons_ent_remove\
move /y .\addons_ent\l10n_sa .\addons_ent_remove\
move /y .\addons_ent\l10n_sg .\addons_ent_remove\
move /y .\addons_ent\l10n_sg_reports .\addons_ent_remove\
move /y .\addons_ent\l10n_si .\addons_ent_remove\
move /y .\addons_ent\l10n_si_reports .\addons_ent_remove\
move /y .\addons_ent\l10n_syscohada .\addons_ent_remove\
move /y .\addons_ent\l10n_th .\addons_ent_remove\
move /y .\addons_ent\l10n_th_reports .\addons_ent_remove\
move /y .\addons_ent\l10n_tr .\addons_ent_remove\
move /y .\addons_ent\l10n_uk .\addons_ent_remove\
move /y .\addons_ent\l10n_uk_reports .\addons_ent_remove\
move /y .\addons_ent\l10n_us .\addons_ent_remove\
move /y .\addons_ent\l10n_us_check_printing .\addons_ent_remove\
move /y .\addons_ent\l10n_us_reports .\addons_ent_remove\
move /y .\addons_ent\l10n_uy .\addons_ent_remove\
move /y .\addons_ent\l10n_uy_reports .\addons_ent_remove\
move /y .\addons_ent\l10n_ve .\addons_ent_remove\
move /y .\addons_ent\l10n_vn .\addons_ent_remove\
move /y .\addons_ent\l10n_vn_reports .\addons_ent_remove\

